//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFERMEDADES
    {
        public ENFERMEDADES()
        {
            this.LISTAENFERMOS = new HashSet<LISTAENFERMOS>();
        }
    
        public int IDEnfermedad { get; set; }
        public string Enfermedad { get; set; }
        public string Dolencia { get; set; }
        public Nullable<int> Reloj { get; set; }
        public string Cura { get; set; }
    
        public virtual ICollection<LISTAENFERMOS> LISTAENFERMOS { get; set; }
    }
}
