//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES
    {
        public PACIENTES()
        {
            this.LISTAENFERMOS = new HashSet<LISTAENFERMOS>();
        }
    
        public int IDPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Reloj { get; set; }
        public Nullable<int> IDEnfermedad { get; set; }
        public string Baja { get; set; }
        public string Eliminado { get; set; }
    
        public virtual ICollection<LISTAENFERMOS> LISTAENFERMOS { get; set; }
    }
}
